DirectoryPath: public
CheckDoctype: true
CheckFavicon: false
CheckImages: true
CheckLinks: false
CheckScripts: false
CheckMeta: false
CheckDuplicateIDs: true
IgnoreURLs:
  - "^https://blackorder.github.io"
